function cellInfo = Mdl_TuDelftOLFunction(varargin) 
% MDL_TUDELFTOLFUNCTION returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

%  busInfo = Simulink.Bus.createObject...
%   ('MdLCtrl_Baseline',...
%   'MdLCtrl_Baseline/BusOutCtrl',...
%   'MdLCtrl_BaselineFunction');

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'slBus1', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'wind_mpers', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'GenSpd_radpers', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RotSpd_radpers', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ydotdot_mpers2', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'xdotdot_mpers2', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'zetadotdot_mpers2', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ThetaS_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'GenPwr_kW', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'GenTq_Nm', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pitch_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 



if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
