
% Create the bus object
wecs = initModel5MWNREL(0);% Define the bus layout in cell format
cellInfoBus = { ...
  { ...
    'wecsBusType', '', '', 'Auto', '-1', { ...
      {'N', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'Ng', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'mh', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'mbl', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'mb', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'mn', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'mtower', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'mr', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'mt', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'mtb', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'H', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'Jg', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'Jr', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'JrL', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'Js', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'wnb', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'wnt', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'wntsw', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'zetat', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'zetab', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'Kt', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'Bt', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'Ktsw', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'Btsw', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'Kb', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'Bb', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'Ks', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'Bs', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'Rr', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'rb', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
      {'etag', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}';

% Create the bus object in the base workspace
Simulink.Bus.cellToObject(cellInfoBus);

% === Create a Simulink.Parameter that uses this bus ===
% Assume you already have a structure `wecs` in your workspace

wecsParam = Simulink.Parameter;
wecsParam.Value = wecs;
wecsParam.DataType = 'Bus: wecsBusType';
wecsParam.CoderInfo.StorageClass = 'ExportedGlobal';

% === Add both the bus and parameter to your data dictionary ===
dictName = 'DD_Mdl1.sldd';  % replace with your actual .sldd name
dictObj = Simulink.data.dictionary.open(dictName);
sectObj = getSection(dictObj, 'Design Data');

% Add or update parameter entry
if exist(sectObj, 'wecsParam')
    entry = getEntry(sectObj, 'wecs');
    setValue(entry, wecsParam);
else
    addEntry(sectObj, 'wecsBusType', wecsParam);
end

% Save the bus object to the data dictionary as well
%Simulink.Bus.save('wecsBusType', dictName, 'overwrite');

% Save and close the dictionary
saveChanges(dictObj);
close(dictObj);

disp('Bus type ''wecsBusType'' and parameter ''wecs'' added to the data dictionary.');
