% -------------------------------------------------------------------
%  Generated by MATLAB on 8-Jul-2021 15:00:23
%  MATLAB version: 9.7.0.1471314 (R2019b) Update 7
% -------------------------------------------------------------------
                                    

CertificationSettings = struct;
CertificationSettings.Wind = struct;
CertificationSettings.Wind.Type = 2;
CertificationSettings.Wind.T = 400;
CertificationSettings.Wind.Ly = 126;
CertificationSettings.Wind.Lz = 126;
CertificationSettings.Wind.dt = 0.1;
CertificationSettings.Wind.Ny = 20;
CertificationSettings.Wind.Nz = 20;
CertificationSettings.Wind.Class = [1; 2];
CertificationSettings.Wind.Step = 5;
CertificationSettings.Wind.EWS = 60;
CertificationSettings.Wind.EOG = 60;
CertificationSettings.Wind.EDC = 60;
CertificationSettings.Wind.ECG = 60;
CertificationSettings.Wind.StepDuration = 20;
CertificationSettings.Mode = struct;
CertificationSettings.Mode.Type = 1;
CertificationSettings.Mode.Actiontime = 30;
CertificationSettings.Run = struct;
CertificationSettings.Run.WindSpeed = 24;
CertificationSettings.Run.Seeds = 1;
CertificationSettings.Run.Time = 400;
CertificationSettings.Run.SeedNumber = 1;
CertificationSettings.Run.RandomSeed = true;

Control = struct;
Control.ForeAft = struct;
Control.ForeAft.Gain = 0;
Control.ForeAft.MaxPitchAmplitude = 5;
Control.Pitch = struct;
Control.Pitch.Fine = 0.106;
Control.Pitch.Min = -2;
Control.Pitch.Max = 90;
Control.Pitch.Minrate = -13;
Control.Pitch.Maxrate = 13;
Control.Pitch.Kp = -0.003;
Control.Pitch.Scheduled = 1;
Control.Pitch.ScheduledPitchAngles = ...
  [0.0706; 0.1168; 0.1524; 0.183; 0.2116; 0.2385; 0.263; 0.286; 0.308; ...
   0.3284; 0.3488; 0.3691; 0.3895; 0.4083];
Control.Pitch.KpGS = [-0.0164; -0.0107; -0.0083; -0.0068; -0.0057; -0.0049; ...
                      -0.0043; -0.0037; -0.0033; -0.0028; -0.0026; -0.0023; ...
                      -0.002; -0.0017];
Control.Pitch.KiGS = [-0.0027; -0.0027; -0.0026; -0.0025; -0.0024; -0.0024; ...
                      -0.0024; -0.0023; -0.0023; -0.0023; -0.0023; -0.0023; ...
                      -0.0023; -0.0023];
Control.Pitch.Ki = -0.001;
Control.Pitch.StartupPitch = 45;
Control.Pitch.StartupPitchRate = 1;
Control.Pitch.StartupSpeed = 0.25;
Control.Pitch.Notch_beta1 = 0;
Control.Pitch.Notch_beta2 = 0;
Control.Pitch.Notch_wn = 0;
Control.Pitch.Notch_beta1GS = [0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; ...
                               ];
Control.Pitch.Notch_beta2GS = [0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; ...
                               ];
Control.Pitch.Notch_wnGS = [0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0];
Control.Pitch.LowPassCutOffFreq = 3;
Control.Pitch.LowPassCutOffFreqGS = ...
  [3; 3; 3; 3; 3; 3; 3; 3; 3; 3; 3; 3; 3; 3];
Control.Pitch.LowPassOrder = 1;
Control.Pitch.Notch2_beta1GS = [0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; ...
                                0];
Control.Pitch.Notch2_beta2GS = [0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; ...
                                0];
Control.Pitch.Notch2_wnGS = [0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0];
Control.Pitch.Notch2_beta1 = 0;
Control.Pitch.Notch2_beta2 = 0;
Control.Pitch.Notch2_wn = 0;
Control.Torque = struct;
Control.Torque.Demanded = 43529;
Control.Torque.Limit = 47403;
Control.Torque.Slewrate = 20000;
Control.Torque.OptGain = 2.3323;
Control.Torque.SpeedA = 670;
Control.Torque.SpeedB = 871;
Control.Torque.SpeedC = 1162;
Control.Torque.SpeedB2 = 1136;
Control.Torque.Min = 200;
Control.Torque.LowPassCutOffFreq = 3;
Control.Brake = struct;
Control.Brake.Deploytime = 0.6;
Control.Brake.Torque = 28116;
Control.Brake.Delay = 1.5;
Control.WindSpeed = struct;
Control.WindSpeed.Cutin = 4;
Control.WindSpeed.Cutout = 25;
Control.DT = 0.008;

Drivetrain = struct;
Drivetrain.Generator = struct;
Drivetrain.Generator.Efficiency = 0.944;
Drivetrain.Generator.HSSInertia = 534.116;
Drivetrain.Gearbox = struct;
Drivetrain.Gearbox.Ratio = 97;
Drivetrain.Gearbox.Efficiency = 1;

P_InitAngle = 0.106;

