function cellInfo = MdLCtrl_BaselineFunction(varargin) 
% MDLCTRL_BASELINEFUNCTION returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'slBus2', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'RefBlPitch1', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RefBlPitch2', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RefBlPitch3', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RefGenTq', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
